theme: jekyll-theme-cayman
title: MoneyTrack - Documentos Legales
description: Documentación legal de la aplicación MoneyTrack
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/aab1251/MoneyTrack-Legal

